# Generated by Django 6.0 on 2026-03-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenovo',
            name='series_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
